"use strict";
!function(){
  let o,e,r,t,s,a,i,n,l;l=isDarkStyle?(
    o=config.colors_dark.cardColor,
    e=config.colors_dark.headingColor,
    r=config.colors_dark.textMuted,
    s=config.colors_dark.borderColor,
    t="dark",
    a="#4f51c0",
    i="#595cd9",
    n="#8789ff",
    "#c3c4ff"
  ):(
      o=config.colors.cardColor,
      e=config.colors.headingColor,
      r=config.colors.textMuted,
      s=config.colors.borderColor,
      t="",
      a="#e1e2ff",
      i="#c3c4ff",
      n="#a5a7ff",
      "#696cff"
    );
    var d=document.querySelector("#visitorsChart"),
    d=(null!==d&&new ApexCharts(d,c).render(),document.querySelector("#totalIncomeChart")),
    c={
          chart:{
            height:250,
            type:"area",
            toolbar:!1,
            dropShadow:{
              enabled:!0,
              top:14,
              left:2,
              blur:3,
              color:config.colors.primary,
              opacity:.15
            }
          },
          series:[{data:[3350,3350,4800,4800,2950,2950,1800,1800,3750,3750,5700,5700]}],
          dataLabels:{
            enabled:!1
          },
          stroke:{
            width:3,
            curve:"straight"
          },
          colors:[config.colors.primary],
          fill:{
            type:"gradient",
            gradient:{
              shade:t,
              shadeIntensity:.8,
              opacityFrom:.7,
              opacityTo:.25,
              stops:[0,95,100]
            }
          },
          grid:{
            show:!0,
            borderColor:s,
            padding:{
              top:-15,
              bottom:-10,
              left:0,
              right:0
            }
          },
          xaxis:{
            categories:["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],
            labels:{
              offsetX:0,
              style:{
                colors:r,
                fontSize:"13px"
              }
            },
            axisBorder:{
              show:!1
            },
            axisTicks:{
              show:!1
            },
            lines:
            {
              show:!1
            }
          },
          yaxis:{
            labels:{
              offsetX:-15,
              formatter:function(o){
                return"$"+parseInt(o/1e3)+"k"
              },
              style:{
                fontSize:"13px",
                colors:r
              }
            },
            min:1e3,
            max:6e3,
            tickAmount:5
          }
        },
    d=(null!==d&&new ApexCharts(d,c).render(),document.querySelector("#totalBalanceChart")),
    c={
      series:[{
        data:[137,210,160,275,205,315]
      }],
      chart:{
        height:250,
        parentHeightOffset:0,
        parentWidthOffset:0,
        type:"line",
        dropShadow:{
          enabled:!0,
          top:10,
          left:5,
          blur:3,
          color:config.colors.warning,
          opacity:.15
        },
        toolbar:{
          show:!1
        }
      },
      dataLabels:{
        enabled:!1
      },
      stroke:{
        width:4,
        curve:"smooth"},
        legend:{
          show:!1
        },
        colors:[config.colors.warning],
        markers:{
          size:6,
          colors:"transparent",
          strokeColors:"transparent",
          strokeWidth:4,
          discrete:[{
            fillColor:config.colors.white,
            seriesIndex:0,
            dataPointIndex:5,
            strokeColor:config.colors.warning,
            strokeWidth:8,
            size:6,
            radius:8
          }],
          hover:{
            size:7
          }
        },
        grid:{
          show:!1,
          padding:{
            top:-10,
            left:0,
            right:0,
            bottom:10
          }
        },
        xaxis:{
          categories:["Jan","Feb","Mar","Apr","May","Jun"],
          axisBorder:{
            show:!1
          },
          axisTicks:{
            show:!1
          },
          labels:{
            show:!0,
            style:{
              fontSize:"13px",
              colors:r
            }
          }
        },
        yaxis:{
          labels:{
            show:!1
          }
        }
      };
      null!==d&&new ApexCharts(d,c).render()
}();
